const free_email_provider_domains = 
`10minutemail.com
20minutemail.com
30minutemail.com
trbvm.com
mailcatch.com
mailinator.com
sharklasers.com
spam4.me
temp-mail.org
yopmail.com
mailnesia.com
guerrillamail.com
getairmail.com
throwawaymail.com
dispostable.com
mytrashmail.com
mintemail.com
spamgourmet.com
emailondeck.com
maildrop.cc
mailexpire.com
mailsac.com
trashmail.com
tempail.com
tempmailaddress.com
mailtemp.info
nospamfor.us
nowmymail.com
mailnull.com
spambox.us
tempmail.de
spamfree24.org
spaml.de
mohmal.com
mailslite.com
nobulk.com
koszmail.pl
tempail.com
10minutemail.net
tempmailaddress.com
mailexpire.com
tempmailbox.net
spamfree24.net
spamfree24.info
spamfree24.de
spamfree24.com`;

export const free_email_provider_set = new Set(free_email_provider_domains.split('\n'));
